apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: yatest
  name: sqlbackupgamedatabase
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sqlbackupgamedatabase
            image: git.systementor.se/ahlin.erik/batchsql
            env:
              - name: sql_host
                value: mysqlserver1  
              - name: sql_user
                value: root
              - name: sql_password
                value: hejsan123   
              - name: sql_database
                value: gamedatabase
          imagePullSecrets:
          - name: regcred
          restartPolicy: OnFailure